version: '3.3'

volumes:
  pg_data:
  static:
  media:
services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: 3kvs3/foodgram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media
    depends_on:
      - db
  frontend:
    image: 3kvs3/foodgram_frontend
    # command: cp -r build result_build
    command: cp -r /app/build/. /frontend_static/
    volumes:
      # - ../frontend/:/app/result_build/
      - static:/frontend_static
  nginx:
    image: 3kvs3/foodgram_nginx
    env_file: .env
    ports:
      - "8090:80"
    volumes:
      # - ./nginx_dev.conf:/etc/nginx/conf.d/default.conf
      # - ../frontend/build:/usr/share/nginx/html/
      # - ../docs/:/usr/share/nginx/html/api/docs/
      # - static:/staticfiles/
      # - media:/media
      - ./docs/:/usr/share/nginx/html/api/docs/
      - static:/staticfiles/
      - media:/media
    depends_on:
      - backend
