# Generated by Django 4.2.11 on 2024-04-17 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram_api', '0003_alter_favorite_options_alter_shoppinglist_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='images/'),
        ),
    ]
