# Generated by Django 3.2.16 on 2024-03-23 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_subscribed',
            field=models.BooleanField(default=0, verbose_name='Подписан'),
            preserve_default=False,
        ),
    ]
