# Generated by Django 3.2.16 on 2024-03-23 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_myuser_is_subscribed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='is_subscribed',
            field=models.BooleanField(default=False, verbose_name='Подписан'),
        ),
    ]
